name: 'Env variables'
on: push

env:
  WF_ENV: 'Available to all jobs'
  SECRET_ENV: '${{secrets.apiKey}}' #You can configure at repository configuration on the secret tab, all secrets can be accessed using the secrets object

jobs:
  log-env:
    runs-on: ubuntu-latest
    env:
      SCOPED_JOB_ENV: 'This env is only available on this job steps'
    steps:
      - name: "Log env variable"
        env:
          SCOPED_STEP_ENV: "This env is only available in this job step"
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "SCOPED_JOB_ENV: ${SCOPED_JOB_ENV}"
          echo "SCOPED_STEP_ENV: ${SCOPED_STEP_ENV}"
          echo "SECRET_ENV: ${SECRET_ENV}"
          echo "SECRET_ENV_AS_WELL: ${{secrets.apiKey}}"


#more about env and default github envs here
#https://docs.github.com/en/actions/learn-github-actions/environment-variables