# name: 'Actions Workflow'
# on: ["push"]

# jobs:
#   github-action:
#     runs-on: ubuntu-latest
#     steps:
#       - name: 'Js action'
#         id: greet
#         uses: actions/hello-world-javascript-action@master
#         with:
#           who-to-greet: "Hiran Junior"
#       - name: 'Loggin greeting time'
#         run: echo "${{ steps.greet.outputs.time }}"
     
