# name: 'First workflow'
# on: [push]
# jobs:
#   run-shell-command:
#     runs-on: ubuntu-latest
#     steps:
#       - name: echo string
#         run: echo "Hello World github actions"
#       - name: multiline script
#         run: |
#           node -v
#           npm -v
#       - name: Python command
#         run: |
#           print("Hello World I'm using python inside github actions")
#         shell: python
#   run-windows-commands:
#     runs-on: windows-latest
#     steps:
#       - name: Directory powershell
#         run: Get-Location
#       - name: Directory bash
#         run: pwd
#         shell: bash
#     needs:
#       - "run-shell-command"